/**
 * @generated by scripts/set-rn-version.js
 *
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
<<<<<<< HEAD:packages/react-native-codegen/src/parsers/parsers-utils.js
 * @format
 * @flow strict
 */

'use strict';

function nullGuard<T>(fn: () => T): ?T {
  return fn();
}

module.exports = {
  nullGuard,
=======
 * @flow strict
 */

exports.version = {
  major: 0,
  minor: 68,
  patch: 2,
  prerelease: null,
>>>>>>> v0.68.2-android14-support:Libraries/Core/ReactNativeVersion.js
};
