/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by scripts/releases/set-version.js
 */

#import "RCTVersion.h"

NSString* const RCTVersionMajor = @"major";
NSString* const RCTVersionMinor = @"minor";
NSString* const RCTVersionPatch = @"patch";
NSString* const RCTVersionPrerelease = @"prerelease";


NSDictionary* RCTGetReactNativeVersion(void)
{
  static NSDictionary* __rnVersion;
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^(void){
    __rnVersion = @{
<<<<<<< HEAD:packages/react-native/React/Base/RCTVersion.m
                  RCTVersionMajor: @(1000),
                  RCTVersionMinor: @(0),
                  RCTVersionPatch: @(0),
=======
                  RCTVersionMajor: @(0),
                  RCTVersionMinor: @(68),
                  RCTVersionPatch: @(2),
>>>>>>> v0.68.2-android14-support:React/Base/RCTVersion.m
                  RCTVersionPrerelease: [NSNull null],
                  };
  });
  return __rnVersion;
}
